import bcrypt from 'bcryptjs';
import { 
  User, Facility, Asset, Technician, Sla, SlaPolicy, WorkOrder, 
  ServiceRequest, Part, AuditLog, WorkOrderStatus, RoleName, Priority,
  FacilityInventory, InventoryHistory, Customer 
} from './types';

// Pre-hashed passwords for demo/foundation accounts ("password123")
const DEFAULT_PASSWORD_HASH = bcrypt.hashSync('password123', 10);

export const SEED_USERS: User[] = [
  {
    id: 'u-super-1',
    organizationId: 'org-apex-1',
    email: 'superadmin@keystone.io',
    passwordHash: DEFAULT_PASSWORD_HASH,
    firstName: 'Sarah',
    lastName: 'Vance',
    roles: ['SUPER_ADMIN', 'ADMIN'],
    isActive: true,
  },
  {
    id: 'u-admin-1',
    organizationId: 'org-apex-1',
    email: 'admin@keystone.io',
    passwordHash: DEFAULT_PASSWORD_HASH,
    firstName: 'Michael',
    lastName: 'Scott',
    roles: ['ADMIN'],
    isActive: true,
  },
  {
    id: 'u-dispatcher-1',
    organizationId: 'org-apex-1',
    email: 'dispatcher@keystone.io',
    passwordHash: DEFAULT_PASSWORD_HASH,
    firstName: 'Marcus',
    lastName: 'Chen',
    roles: ['DISPATCHER'],
    isActive: true,
  },
  {
    id: 'u-tech-1',
    organizationId: 'org-apex-1',
    email: 'tech.davis@keystone.io',
    passwordHash: DEFAULT_PASSWORD_HASH,
    firstName: 'Elena',
    lastName: 'Reyes',
    roles: ['TECHNICIAN'],
    isActive: true,
  },
  {
    id: 'u-tech-2',
    organizationId: 'org-apex-1',
    email: 'tech.miller@keystone.io',
    passwordHash: DEFAULT_PASSWORD_HASH,
    firstName: 'Jamal',
    lastName: 'Miller',
    roles: ['TECHNICIAN'],
    isActive: true,
  },
  {
    id: 'u-customer-1',
    organizationId: 'org-apex-1',
    email: 'facilitymgr@globalfin.com',
    passwordHash: DEFAULT_PASSWORD_HASH,
    firstName: 'David',
    lastName: 'Kim',
    roles: ['CUSTOMER'],
    isActive: true,
  },
  {
    id: 'u-crossorg-1',
    organizationId: 'org-beta-2',
    email: 'tenant2.admin@externalcorp.com',
    passwordHash: DEFAULT_PASSWORD_HASH,
    firstName: 'Alex',
    lastName: 'Rivers',
    roles: ['ADMIN'],
    isActive: true,
  }
];

export const SEED_FACILITIES: Facility[] = [
  {
    id: 'fac-1',
    organizationId: 'org-apex-1',
    name: 'Apex Tower Manhattan',
    code: 'FAC-NYC-01',
    facilityType: 'COMMERCIAL_HIGH_RISE',
    address: '350 5th Avenue, Floors 12-45',
    city: 'New York',
    state: 'NY',
    postalCode: '10118',
    lat: 40.7484,
    lng: -73.9857,
    totalAssetsCount: 64,
  },
  {
    id: 'fac-2',
    organizationId: 'org-apex-1',
    name: 'Silicon Bay Innovation Campus',
    code: 'FAC-SFO-02',
    facilityType: 'DATA_CENTER_AND_LABS',
    address: '400 Technology Way',
    city: 'San Jose',
    state: 'CA',
    postalCode: '95110',
    lat: 37.3382,
    lng: -121.8863,
    totalAssetsCount: 118,
  },
  {
    id: 'fac-3',
    organizationId: 'org-apex-1',
    name: 'Metro BioTech Research Facility',
    code: 'FAC-BOS-03',
    facilityType: 'CLEANROOM_AND_CLINICAL',
    address: '88 Cambridge Science Park',
    city: 'Boston',
    state: 'MA',
    postalCode: '02142',
    lat: 42.3601,
    lng: -71.0589,
    totalAssetsCount: 42,
  }
];

export const SEED_ASSETS: Asset[] = [
  {
    id: 'ast-1',
    organizationId: 'org-apex-1',
    facilityId: 'fac-1',
    tagNumber: 'AST-HVAC-1001',
    name: 'Trane Centrifugal Chiller 500-Ton',
    category: 'HVAC',
    model: 'CVHE-500-Series',
    serialNumber: 'TRN-8942-X1',
    manufacturer: 'Trane Commercial Systems',
    status: 'DEGRADED',
    criticality: 'CRITICAL',
    locationDetails: 'Roof Mechanical Penthouse A',
  },
  {
    id: 'ast-2',
    organizationId: 'org-apex-1',
    facilityId: 'fac-1',
    tagNumber: 'AST-ELEV-2044',
    name: 'Otis SkyRise High-Speed Elevator Bank C',
    category: 'ELEVATOR',
    model: 'SkyRise-Gen2-4000',
    serialNumber: 'OTS-2023-998',
    manufacturer: 'Otis Elevator Company',
    status: 'OPERATIONAL',
    criticality: 'HIGH',
    locationDetails: 'Core Shaft Passenger Bank North',
  },
  {
    id: 'ast-3',
    organizationId: 'org-apex-1',
    facilityId: 'fac-2',
    tagNumber: 'AST-PWR-3012',
    name: 'Cummins Emergency Diesel Generator 1.5MW',
    category: 'ELECTRICAL',
    model: 'QSK50-G4-1500',
    serialNumber: 'CUM-50-88741',
    manufacturer: 'Cummins Power Systems',
    status: 'OPERATIONAL',
    criticality: 'CRITICAL',
    locationDetails: 'Sub-Basement Backup Vault B2',
  },
  {
    id: 'ast-4',
    organizationId: 'org-apex-1',
    facilityId: 'fac-3',
    tagNumber: 'AST-BAS-4009',
    name: 'Johnson Controls Metasys DDC Server',
    category: 'BUILDING_AUTOMATION',
    model: 'NAE-55-Server',
    serialNumber: 'JCI-NAE-7734',
    manufacturer: 'Johnson Controls',
    status: 'OPERATIONAL',
    criticality: 'HIGH',
    locationDetails: 'Server Room 302',
  }
];

export const SEED_TECHNICIANS: Technician[] = [
  {
    id: 'tech-1',
    userId: 'u-tech-1',
    organizationId: 'org-apex-1',
    employeeCode: 'EMP-7701',
    name: 'Elena Reyes',
    email: 'tech.davis@keystone.io',
    phone: '(555) 234-8901',
    skills: ['HVAC Chiller Master', 'EPA Universal', 'VFD Drives', 'Johnson Controls BAS'],
    certifications: ['Master HVAC License #9941', 'NATE Certified Commercial Specialist'],
    hourlyRate: 85.00,
    status: 'ON_SITE',
    currentAssignedCount: 2,
    lat: 40.7484,
    lng: -73.9857,
  },
  {
    id: 'tech-2',
    userId: 'u-tech-2',
    organizationId: 'org-apex-1',
    employeeCode: 'EMP-7702',
    name: 'Jamal Miller',
    email: 'tech.miller@keystone.io',
    phone: '(555) 345-6789',
    skills: ['Commercial Electrical', 'Switchgear 480V', 'Cummins Generator Specialist', 'Infrared Thermography'],
    certifications: ['Master Electrician License #4412', 'NFPA 70E Arc Flash Certified'],
    hourlyRate: 92.00,
    status: 'AVAILABLE',
    currentAssignedCount: 1,
    lat: 37.3382,
    lng: -121.8863,
  },
  {
    id: 'tech-3',
    userId: 'u-tech-3',
    organizationId: 'org-apex-1',
    employeeCode: 'EMP-7703',
    name: 'Liam Gallagher',
    email: 'liam.g@keystone.io',
    phone: '(555) 456-7890',
    skills: ['Commercial Plumbing', 'Fire Suppression Sprinklers', 'Backflow Prevention'],
    certifications: ['Master Plumber NY-6612', 'NICET Fire Protection Level II'],
    hourlyRate: 78.00,
    status: 'IN_TRANSIT',
    currentAssignedCount: 2,
    lat: 42.3601,
    lng: -71.0589,
  }
];

export const SEED_SLA_POLICIES: SlaPolicy[] = [
  {
    id: 'sla-crit-247',
    organizationId: 'org-apex-1',
    name: 'Mission-Critical 24/7 Enterprise Tier',
    priority: 'CRITICAL',
    responseTimeMinutes: 30,
    resolutionTimeMinutes: 240, // 4 hours
    businessHoursOnly: false,
    escalationRules: [
      { id: 'esc-1', triggerPercentage: 50, action: 'NOTIFY_DISPATCHER', description: 'Alert dispatcher when 50% response time elapsed without technician acceptance' },
      { id: 'esc-2', triggerPercentage: 75, action: 'ESCALATE_SUPERVISOR', description: 'Escalate to regional operations manager when 75% resolution time elapsed' },
      { id: 'esc-3', triggerPercentage: 90, action: 'PAGE_ONCALL', description: 'Page on-call master technician when 90% resolution elapsed' },
    ],
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'sla-high-std',
    organizationId: 'org-apex-1',
    name: 'High Priority Standard Facility SLA',
    priority: 'HIGH',
    responseTimeMinutes: 60,
    resolutionTimeMinutes: 480, // 8 hours
    businessHoursOnly: true, // 8am - 6pm
    escalationRules: [
      { id: 'esc-4', triggerPercentage: 75, action: 'NOTIFY_DISPATCHER', description: 'Alert dispatcher if technician has not reached site within 75% response window' },
      { id: 'esc-5', triggerPercentage: 90, action: 'ESCALATE_SUPERVISOR', description: 'Supervisor escalation for nearing breach' },
    ],
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'sla-med-ops',
    organizationId: 'org-apex-1',
    name: 'Commercial Standard Operations (Medium)',
    priority: 'MEDIUM',
    responseTimeMinutes: 120,
    resolutionTimeMinutes: 1440, // 24 hours
    businessHoursOnly: true,
    escalationRules: [
      { id: 'esc-6', triggerPercentage: 80, action: 'NOTIFY_DISPATCHER', description: 'Reminder notification when 80% resolution window elapsed' },
    ],
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'sla-low-maint',
    organizationId: 'org-apex-1',
    name: 'Scheduled Routine Maintenance (Low)',
    priority: 'LOW',
    responseTimeMinutes: 240,
    resolutionTimeMinutes: 4320, // 72 hours
    businessHoursOnly: true,
    escalationRules: [
      { id: 'esc-7', triggerPercentage: 90, action: 'NOTIFY_DISPATCHER', description: 'Weekly backlog review notification' },
    ],
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'sla-bio-custom',
    organizationId: 'org-apex-1',
    name: 'BioHealth Labs Research Wing Strict SLA',
    priority: 'CRITICAL',
    customerId: 'cust-2',
    customerName: 'BioHealth Laboratories',
    facilityId: 'fac-3',
    facilityName: 'Metro BioTech Research Facility',
    responseTimeMinutes: 20,
    resolutionTimeMinutes: 180, // 3 hours
    businessHoursOnly: false,
    escalationRules: [
      { id: 'esc-8', triggerPercentage: 50, action: 'PAGE_ONCALL', description: 'Immediate lab hazard page to primary bio-safety technician' },
      { id: 'esc-9', triggerPercentage: 80, action: 'ESCALATE_SUPERVISOR', description: 'Direct notice to VP of Facility Operations' },
    ],
    createdAt: '2026-02-15T00:00:00.000Z',
    updatedAt: '2026-02-15T00:00:00.000Z',
  }
];

export const SEED_SLAS: Sla[] = SEED_SLA_POLICIES.map(p => ({
  id: p.id,
  organizationId: p.organizationId,
  name: p.name,
  priority: p.priority,
  responseTimeMinutes: p.responseTimeMinutes,
  resolutionTimeMinutes: p.resolutionTimeMinutes,
}));

export const SEED_PARTS: Part[] = [
  {
    id: 'prt-1',
    organizationId: 'org-apex-1',
    partNumber: 'TRN-EXP-V99',
    name: 'Thermal Expansion Valve 15-Ton R-410A',
    description: 'Precision thermostatic expansion valve with balanced port construction for variable refrigerant flow systems.',
    category: 'HVAC',
    unitCost: 145.00,
    unitPrice: 285.00,
    supplier: 'Trane Supply Wholesale',
    isActive: true,
    stockOnHand: 14,
    reorderLevel: 5,
    minStock: 3,
  },
  {
    id: 'prt-2',
    organizationId: 'org-apex-1',
    partNumber: 'SQD-CNT-40A',
    name: 'Square D 3-Pole 40A 24V Contactor',
    description: 'Definite purpose magnetic contactor with 24V AC coil and silver cadmium oxide contacts for motor compressor circuits.',
    category: 'ELECTRICAL',
    unitCost: 38.50,
    unitPrice: 85.00,
    supplier: 'Schneider Electric Direct',
    isActive: true,
    stockOnHand: 32,
    reorderLevel: 10,
    minStock: 6,
  },
  {
    id: 'prt-3',
    organizationId: 'org-apex-1',
    partNumber: 'FLT-HEPA-2424',
    name: 'High-Efficiency HEPA Filter 24x24x12',
    description: 'Commercial cleanroom Grade 99.97% DOP rated HEPA filter for clean air handling and biosafety exhaust systems.',
    category: 'FILTRATION',
    unitCost: 72.00,
    unitPrice: 140.00,
    supplier: 'AAF Flanders Industrial',
    isActive: true,
    stockOnHand: 48,
    reorderLevel: 15,
    minStock: 8,
  },
  {
    id: 'prt-4',
    organizationId: 'org-apex-1',
    partNumber: 'JCI-SNS-T100',
    name: 'Johnson Controls 10k NTC Duct Temp Sensor',
    description: 'High-precision thermistor sensor element in aluminum probe enclosure for Metasys BAS system integration.',
    category: 'BUILDING_AUTOMATION',
    unitCost: 28.00,
    unitPrice: 65.00,
    supplier: 'Johnson Controls Building Supply',
    isActive: true,
    stockOnHand: 18,
    reorderLevel: 8,
    minStock: 4,
  },
  {
    id: 'prt-5',
    organizationId: 'org-apex-1',
    partNumber: 'WIL-SEAL-P55',
    name: 'Wilo Mechanical Shaft Seal Kit 2-Inch',
    description: 'Silicon carbide vs silicon carbide mechanical seal for primary chilled water pumps with Viton elastomers.',
    category: 'PLUMBING',
    unitCost: 95.00,
    unitPrice: 190.00,
    supplier: 'Wilo USA Distribution',
    isActive: true,
    stockOnHand: 4, // low stock
    reorderLevel: 6,
    minStock: 2,
  },
  {
    id: 'prt-6',
    organizationId: 'org-apex-1',
    partNumber: 'BEL-ACT-24V',
    name: 'Belimo Direct-Coupled Damper Actuator 24V',
    description: 'Non-spring return electronic actuator with 133 in-lb torque and 0-10V proportional feedback.',
    category: 'HVAC',
    unitCost: 110.00,
    unitPrice: 225.00,
    supplier: 'Belimo Americas',
    isActive: true,
    stockOnHand: 2, // low stock!
    reorderLevel: 5,
    minStock: 3,
  }
];

export const SEED_FACILITY_INVENTORY: FacilityInventory[] = [
  // Apex Tower Manhattan (fac-1)
  {
    id: 'inv-fac1-prt1',
    organizationId: 'org-apex-1',
    facilityId: 'fac-1',
    facilityName: 'Apex Tower Manhattan',
    partId: 'prt-1',
    partNumber: 'TRN-EXP-V99',
    partName: 'Thermal Expansion Valve 15-Ton R-410A',
    category: 'HVAC',
    binLocation: 'Room B2 - Aisle 3 - Shelf A',
    stockOnHand: 8,
    reservedQuantity: 1,
    minStock: 3,
    reorderLevel: 5,
    unitCost: 145.00,
    unitPrice: 285.00,
    supplier: 'Trane Supply Wholesale',
    lastRestockedAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
  },
  {
    id: 'inv-fac1-prt2',
    organizationId: 'org-apex-1',
    facilityId: 'fac-1',
    facilityName: 'Apex Tower Manhattan',
    partId: 'prt-2',
    partNumber: 'SQD-CNT-40A',
    partName: 'Square D 3-Pole 40A 24V Contactor',
    category: 'ELECTRICAL',
    binLocation: 'Room B2 - Aisle 1 - Bin 14',
    stockOnHand: 16,
    reservedQuantity: 0,
    minStock: 6,
    reorderLevel: 10,
    unitCost: 38.50,
    unitPrice: 85.00,
    supplier: 'Schneider Electric Direct',
    lastRestockedAt: '2026-08-15T14:30:00.000Z',
    updatedAt: '2026-08-15T14:30:00.000Z',
  },
  {
    id: 'inv-fac1-prt3',
    organizationId: 'org-apex-1',
    facilityId: 'fac-1',
    facilityName: 'Apex Tower Manhattan',
    partId: 'prt-3',
    partNumber: 'FLT-HEPA-2424',
    partName: 'High-Efficiency HEPA Filter 24x24x12',
    category: 'FILTRATION',
    binLocation: 'Room B3 - Bulk Rack 4',
    stockOnHand: 24,
    reservedQuantity: 2,
    minStock: 8,
    reorderLevel: 15,
    unitCost: 72.00,
    unitPrice: 140.00,
    supplier: 'AAF Flanders Industrial',
    lastRestockedAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
  },
  {
    id: 'inv-fac1-prt5',
    organizationId: 'org-apex-1',
    facilityId: 'fac-1',
    facilityName: 'Apex Tower Manhattan',
    partId: 'prt-5',
    partNumber: 'WIL-SEAL-P55',
    partName: 'Wilo Mechanical Shaft Seal Kit 2-Inch',
    category: 'PLUMBING',
    binLocation: 'Room B2 - Cabinet 2',
    stockOnHand: 2, // Low stock!
    reservedQuantity: 0,
    minStock: 2,
    reorderLevel: 4,
    unitCost: 95.00,
    unitPrice: 190.00,
    supplier: 'Wilo USA Distribution',
    lastRestockedAt: '2026-07-10T11:00:00.000Z',
    updatedAt: '2026-07-10T11:00:00.000Z',
  },
  {
    id: 'inv-fac1-prt6',
    organizationId: 'org-apex-1',
    facilityId: 'fac-1',
    facilityName: 'Apex Tower Manhattan',
    partId: 'prt-6',
    partNumber: 'BEL-ACT-24V',
    partName: 'Belimo Direct-Coupled Damper Actuator 24V',
    category: 'HVAC',
    binLocation: 'Room B2 - Aisle 4 - Shelf C',
    stockOnHand: 1, // Critical low stock!
    reservedQuantity: 0,
    minStock: 2,
    reorderLevel: 3,
    unitCost: 110.00,
    unitPrice: 225.00,
    supplier: 'Belimo Americas',
    lastRestockedAt: '2026-06-25T16:00:00.000Z',
    updatedAt: '2026-06-25T16:00:00.000Z',
  },

  // Silicon Valley Data Center (fac-2)
  {
    id: 'inv-fac2-prt2',
    organizationId: 'org-apex-1',
    facilityId: 'fac-2',
    facilityName: 'Silicon Valley Data Center Campus',
    partId: 'prt-2',
    partNumber: 'SQD-CNT-40A',
    partName: 'Square D 3-Pole 40A 24V Contactor',
    category: 'ELECTRICAL',
    binLocation: 'Substation Bay 1 - Bin 08',
    stockOnHand: 12,
    reservedQuantity: 0,
    minStock: 4,
    reorderLevel: 8,
    unitCost: 38.50,
    unitPrice: 85.00,
    supplier: 'Schneider Electric Direct',
    lastRestockedAt: '2026-08-10T08:00:00.000Z',
    updatedAt: '2026-08-10T08:00:00.000Z',
  },
  {
    id: 'inv-fac2-prt4',
    organizationId: 'org-apex-1',
    facilityId: 'fac-2',
    facilityName: 'Silicon Valley Data Center Campus',
    partId: 'prt-4',
    partNumber: 'JCI-SNS-T100',
    partName: 'Johnson Controls 10k NTC Duct Temp Sensor',
    category: 'BUILDING_AUTOMATION',
    binLocation: 'NOC Tech Spares - Shelf 2',
    stockOnHand: 10,
    reservedQuantity: 0,
    minStock: 3,
    reorderLevel: 6,
    unitCost: 28.00,
    unitPrice: 65.00,
    supplier: 'Johnson Controls Building Supply',
    lastRestockedAt: '2026-08-18T13:00:00.000Z',
    updatedAt: '2026-08-18T13:00:00.000Z',
  },

  // Metro BioTech Research Facility (fac-3)
  {
    id: 'inv-fac3-prt3',
    organizationId: 'org-apex-1',
    facilityId: 'fac-3',
    facilityName: 'Metro BioTech Research Facility',
    partId: 'prt-3',
    partNumber: 'FLT-HEPA-2424',
    partName: 'High-Efficiency HEPA Filter 24x24x12',
    category: 'FILTRATION',
    binLocation: 'Lab Wing C - Clean Storage',
    stockOnHand: 18,
    reservedQuantity: 0,
    minStock: 6,
    reorderLevel: 10,
    unitCost: 72.00,
    unitPrice: 140.00,
    supplier: 'AAF Flanders Industrial',
    lastRestockedAt: '2026-08-12T11:00:00.000Z',
    updatedAt: '2026-08-12T11:00:00.000Z',
  },
  {
    id: 'inv-fac3-prt4',
    organizationId: 'org-apex-1',
    facilityId: 'fac-3',
    facilityName: 'Metro BioTech Research Facility',
    partId: 'prt-4',
    partNumber: 'JCI-SNS-T100',
    partName: 'Johnson Controls 10k NTC Duct Temp Sensor',
    category: 'BUILDING_AUTOMATION',
    binLocation: 'Lab Central Automation Cage',
    stockOnHand: 8,
    reservedQuantity: 0,
    minStock: 3,
    reorderLevel: 5,
    unitCost: 28.00,
    unitPrice: 65.00,
    supplier: 'Johnson Controls Building Supply',
    lastRestockedAt: '2026-08-14T15:00:00.000Z',
    updatedAt: '2026-08-14T15:00:00.000Z',
  }
];

export const SEED_INVENTORY_HISTORY: InventoryHistory[] = [
  {
    id: 'invh-1',
    organizationId: 'org-apex-1',
    facilityId: 'fac-1',
    facilityName: 'Apex Tower Manhattan',
    partId: 'prt-1',
    partNumber: 'TRN-EXP-V99',
    partName: 'Thermal Expansion Valve 15-Ton R-410A',
    changeType: 'RESTOCK',
    quantityChanged: 5,
    previousStock: 4,
    newStock: 9,
    referenceId: 'PO-2026-0912',
    performedBy: 'Marcus Chen (Dispatcher)',
    performedByRole: 'DISPATCHER',
    reason: 'Monthly replenishment delivery from Trane Supply',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: 'invh-2',
    organizationId: 'org-apex-1',
    facilityId: 'fac-1',
    facilityName: 'Apex Tower Manhattan',
    partId: 'prt-1',
    partNumber: 'TRN-EXP-V99',
    partName: 'Thermal Expansion Valve 15-Ton R-410A',
    changeType: 'CONSUMPTION',
    quantityChanged: -1,
    previousStock: 9,
    newStock: 8,
    referenceId: 'WO-2026-0881',
    performedBy: 'Elena Reyes (Technician)',
    performedByRole: 'TECHNICIAN',
    reason: 'Allocated to Work Order WO-2026-0881 (Chiller #1 repair)',
    timestamp: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
  }
];

export const SEED_WORK_ORDERS: WorkOrder[] = [
  {
    id: 'wo-101',
    organizationId: 'org-apex-1',
    workOrderNumber: 'WO-2026-0881',
    facilityId: 'fac-1',
    facilityName: 'Apex Tower Manhattan',
    assetId: 'ast-1',
    assetName: 'Trane Centrifugal Chiller 500-Ton',
    assignedTechnicianId: 'tech-1',
    assignedTechnicianName: 'Elena Reyes',
    title: 'High Pressure Sensor Trip on Chiller #1 Compressor Circuit B',
    description: 'Chiller circuit B reported refrigerant pressure threshold alarm (>380 PSI). Auto-tripped offline. Mechanical room ambient temperature climbing rapidly. Requires immediate diagnostic, pressure equalization, and sensor continuity check.',
    status: 'IN_PROGRESS',
    priority: 'CRITICAL',
    category: 'EMERGENCY_REPAIR',
    estimatedDurationHours: 3.5,
    actualDurationHours: 1.8,
    slaResponseDeadline: new Date(Date.now() + 1000 * 60 * 15).toISOString(),
    slaResolutionDeadline: new Date(Date.now() + 1000 * 60 * 150).toISOString(),
    respondedAt: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
    isSlaResponseBreached: false,
    isSlaResolutionBreached: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    parts: [
      {
        id: 'wop-1',
        workOrderId: 'wo-101',
        partId: 'prt-1',
        partNumber: 'TRN-EXP-V99',
        partName: 'Thermal Expansion Valve 15-Ton R-410A',
        quantity: 1,
        unitCost: 145.00,
        totalCost: 145.00,
        unitPrice: 285.00,
        totalPrice: 285.00,
        facilityId: 'fac-1',
        facilityName: 'Apex Tower Manhattan',
        addedAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
        addedBy: 'Elena Reyes (Technician)',
      }
    ],
    timeEntries: [
      {
        id: 'te-1',
        workOrderId: 'wo-101',
        workOrderNumber: 'WO-2026-0881',
        technicianId: 'tech-1',
        technicianName: 'Elena Reyes',
        startTime: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
        endTime: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
        durationMinutes: 30,
        entryType: 'TRAVEL',
        description: 'Dispatched to Apex Tower Mechanical Room. Badged through security.',
        notes: 'Dispatched to Apex Tower Mechanical Room. Badged through security.',
        isBillable: true,
        hourlyRate: 85.00,
        laborCost: 42.50,
        createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      },
      {
        id: 'te-2',
        workOrderId: 'wo-101',
        workOrderNumber: 'WO-2026-0881',
        technicianId: 'tech-1',
        technicianName: 'Elena Reyes',
        startTime: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
        endTime: new Date(Date.now() - 1000 * 60 * 0).toISOString(),
        durationMinutes: 45,
        entryType: 'DIAGNOSIS',
        description: 'Connected manifold gauges. Circuit B head pressure elevated due to faulty modulation valve.',
        notes: 'Connected manifold gauges. Circuit B head pressure elevated due to faulty modulation valve.',
        isBillable: true,
        hourlyRate: 85.00,
        laborCost: 63.75,
        createdAt: new Date(Date.now() - 1000 * 60 * 0).toISOString(),
      }
    ],
    auditLogs: [
      {
        id: 'aud-1',
        organizationId: 'org-apex-1',
        entityName: 'WorkOrder',
        entityId: 'wo-101',
        action: 'CREATED',
        performedBy: 'Marcus Chen (Dispatcher)',
        performedByRole: 'DISPATCHER',
        timestamp: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
        newState: 'NEW',
        notes: 'Work order created from automated telemetry alert.',
      },
      {
        id: 'aud-2',
        organizationId: 'org-apex-1',
        entityName: 'WorkOrder',
        entityId: 'wo-101',
        action: 'STATUS_TRANSITION',
        performedBy: 'Marcus Chen (Dispatcher)',
        performedByRole: 'DISPATCHER',
        timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
        previousState: 'NEW',
        newState: 'TRIAGED',
        notes: 'Verified chiller specs and prioritized SLA Platinum critical.',
      },
      {
        id: 'aud-3',
        organizationId: 'org-apex-1',
        entityName: 'WorkOrder',
        entityId: 'wo-101',
        action: 'ASSIGNED',
        performedBy: 'Marcus Chen (Dispatcher)',
        performedByRole: 'DISPATCHER',
        timestamp: new Date(Date.now() - 1000 * 60 * 85).toISOString(),
        previousState: 'TRIAGED',
        newState: 'ASSIGNED',
        notes: 'Dispatched Elena Reyes (Master HVAC Specialist).',
      },
      {
        id: 'aud-4',
        organizationId: 'org-apex-1',
        entityName: 'WorkOrder',
        entityId: 'wo-101',
        action: 'STATUS_TRANSITION',
        performedBy: 'Elena Reyes (Technician)',
        performedByRole: 'TECHNICIAN',
        timestamp: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
        previousState: 'ASSIGNED',
        newState: 'ACCEPTED',
        notes: 'Technician acknowledged dispatch on mobile client.',
      },
      {
        id: 'aud-5',
        organizationId: 'org-apex-1',
        entityName: 'WorkOrder',
        entityId: 'wo-101',
        action: 'STATUS_TRANSITION',
        performedBy: 'Elena Reyes (Technician)',
        performedByRole: 'TECHNICIAN',
        timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
        previousState: 'ACCEPTED',
        newState: 'IN_PROGRESS',
        notes: 'On site at chiller mechanical deck.',
      }
    ],
    comments: [
      {
        id: 'comm-101',
        entityId: 'wo-101',
        entityType: 'WORK_ORDER',
        authorId: 'user-tech-1',
        authorName: 'Elena Reyes',
        authorRole: 'TECHNICIAN',
        content: 'Compressor Circuit B head pressure currently 395 PSI. Isolating suction valve before removing valve assembly.',
        createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      },
      {
        id: 'comm-102',
        entityId: 'wo-101',
        entityType: 'WORK_ORDER',
        authorId: 'user-disp-1',
        authorName: 'Marcus Chen',
        authorRole: 'DISPATCHER',
        content: 'Tenant notified of temporary chiller load reduction. Tower chilled water setpoint bumped 2 degrees.',
        createdAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
      }
    ],
    attachments: [
      {
        id: 'att-101',
        entityId: 'wo-101',
        entityType: 'WORK_ORDER',
        fileName: 'manifold_gauges_circuit_b.jpg',
        fileSize: 412980,
        fileType: 'image/jpeg',
        url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=60',
        uploadedBy: 'Elena Reyes',
        uploadedByRole: 'TECHNICIAN',
        createdAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
        caption: 'Manifold gauges showing 395 PSI high-side pressure',
      }
    ],
    assignmentHistory: [
      {
        id: 'asg-101',
        workOrderId: 'wo-101',
        technicianId: 'tech-1',
        technicianName: 'Elena Reyes',
        assignedBy: 'Marcus Chen',
        assignedByRole: 'DISPATCHER',
        assignedAt: new Date(Date.now() - 1000 * 60 * 85).toISOString(),
        notes: 'Urgent emergency dispatch. Elena closest certified HVAC tech.',
        status: 'ACTIVE',
      }
    ]
  },
  {
    id: 'wo-102',
    organizationId: 'org-apex-1',
    workOrderNumber: 'WO-2026-0882',
    facilityId: 'fac-2',
    facilityName: 'Silicon Bay Innovation Campus',
    assetId: 'ast-3',
    assetName: 'Cummins Emergency Diesel Generator 1.5MW',
    assignedTechnicianId: 'tech-2',
    assignedTechnicianName: 'Jamal Miller',
    title: 'Quarterly Load-Bank Testing & Automatic Transfer Switch Inspection',
    description: 'Execute mandatory NFPA 110 Level 1 emergency power supply system performance verification under 100% rated load for 4 continuous hours. Record oil pressure, coolant temp, harmonic distortion, and ATS transition times.',
    status: 'ASSIGNED',
    priority: 'HIGH',
    category: 'PREVENTIVE_MAINTENANCE',
    estimatedDurationHours: 5.0,
    actualDurationHours: 0.0,
    slaResponseDeadline: new Date(Date.now() + 1000 * 60 * 180).toISOString(),
    slaResolutionDeadline: new Date(Date.now() + 1000 * 60 * 900).toISOString(),
    isSlaResponseBreached: false,
    isSlaResolutionBreached: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    parts: [],
    timeEntries: [],
    auditLogs: [
      {
        id: 'aud-201',
        organizationId: 'org-apex-1',
        entityName: 'WorkOrder',
        entityId: 'wo-102',
        action: 'CREATED',
        performedBy: 'System Maintenance Scheduler',
        performedByRole: 'ADMIN',
        timestamp: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
        newState: 'NEW',
        notes: 'Generated from recurring preventive maintenance rule.',
      },
      {
        id: 'aud-202',
        organizationId: 'org-apex-1',
        entityName: 'WorkOrder',
        entityId: 'wo-102',
        action: 'STATUS_TRANSITION',
        performedBy: 'Marcus Chen',
        performedByRole: 'DISPATCHER',
        timestamp: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
        previousState: 'NEW',
        newState: 'TRIAGED',
        notes: 'Pre-flight verified ATS permit and campus notification.',
      },
      {
        id: 'aud-203',
        organizationId: 'org-apex-1',
        entityName: 'WorkOrder',
        entityId: 'wo-102',
        action: 'STATUS_TRANSITION',
        performedBy: 'Marcus Chen',
        performedByRole: 'DISPATCHER',
        timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
        previousState: 'TRIAGED',
        newState: 'ASSIGNED',
        notes: 'Assigned Jamal Miller (Master Electrician).',
      }
    ]
  },
  {
    id: 'wo-103',
    organizationId: 'org-apex-1',
    workOrderNumber: 'WO-2026-0879',
    facilityId: 'fac-3',
    facilityName: 'Metro BioTech Research Facility',
    assetId: 'ast-4',
    assetName: 'Johnson Controls Metasys DDC Server',
    assignedTechnicianId: 'tech-3',
    assignedTechnicianName: 'Liam Gallagher',
    title: 'Cleanroom Humidity Differential Sensor Calibration',
    description: 'Cleanroom ISO Class 6 Suite B showing relative humidity drift (+8% tolerance exceedance). Requires recalibration of Vaisala DMP248 transmitters and actuator dampener repositioning.',
    status: 'ON_HOLD',
    priority: 'HIGH',
    category: 'CORRECTIVE_MAINTENANCE',
    estimatedDurationHours: 3.0,
    actualDurationHours: 1.5,
    holdReason: 'Awaiting cleanroom sanitation clearance & specialized NIST-traceable calibration harness from central depot.',
    slaResponseDeadline: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    slaResolutionDeadline: new Date(Date.now() + 1000 * 60 * 240).toISOString(),
    respondedAt: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
    isSlaResponseBreached: false,
    isSlaResolutionBreached: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    parts: [],
    timeEntries: [
      {
        id: 'te-301',
        workOrderId: 'wo-103',
        technicianId: 'tech-3',
        technicianName: 'Liam Gallagher',
        startTime: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
        endTime: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
        durationMinutes: 90,
        entryType: 'DIAGNOSIS',
        isBillable: true,
        hourlyRate: 85,
        laborCost: 127.50,
        notes: 'Tested sensor loop voltage. Found humidity drift on channel 4. Put on hold for calibration tool.',
        createdAt: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
      }
    ],
    auditLogs: [
      {
        id: 'aud-301',
        organizationId: 'org-apex-1',
        entityName: 'WorkOrder',
        entityId: 'wo-103',
        action: 'STATUS_TRANSITION',
        performedBy: 'Liam Gallagher',
        performedByRole: 'TECHNICIAN',
        timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
        previousState: 'IN_PROGRESS',
        newState: 'ON_HOLD',
        notes: 'Placed on hold waiting for specialized NIST-traceable harness.',
      }
    ]
  },
  {
    id: 'wo-104',
    organizationId: 'org-apex-1',
    workOrderNumber: 'WO-2026-0875',
    facilityId: 'fac-1',
    facilityName: 'Apex Tower Manhattan',
    assetId: 'ast-2',
    assetName: 'Otis SkyRise High-Speed Elevator Bank C',
    assignedTechnicianId: 'tech-1',
    assignedTechnicianName: 'Elena Reyes',
    title: 'Door Operator Belt Replacement & Optical Curtain Re-alignment',
    description: 'Elevator Car #3 door sensor intermittent obstruction alarm. Replaced worn drive belt and calibrated 128-beam light curtain.',
    status: 'COMPLETED',
    priority: 'MEDIUM',
    category: 'REPAIR',
    estimatedDurationHours: 2.0,
    actualDurationHours: 1.75,
    slaResponseDeadline: new Date(Date.now() - 1000 * 60 * 720).toISOString(),
    slaResolutionDeadline: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    respondedAt: new Date(Date.now() - 1000 * 60 * 700).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    resolutionNotes: 'Replaced optical sensor transceiver, tensioned drive belt to 45 lbf, performed 5 test floor cycles without fault.',
    isSlaResponseBreached: false,
    isSlaResolutionBreached: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 800).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    parts: [],
    timeEntries: [],
    auditLogs: []
  },
  {
    id: 'wo-105',
    organizationId: 'org-apex-1',
    workOrderNumber: 'WO-2026-0870',
    facilityId: 'fac-2',
    facilityName: 'Silicon Bay Innovation Campus',
    title: 'Main Server Room Fire Suppression Pre-Action Dry Pipe Pressure Inspection',
    description: 'Verify 35 PSI supervisory air pressure in dry pipe nitrogen suppression line. Inspect tamper switches and annunciator panel.',
    status: 'VERIFIED',
    priority: 'LOW',
    category: 'INSPECTION',
    estimatedDurationHours: 1.5,
    actualDurationHours: 1.2,
    slaResponseDeadline: new Date(Date.now() - 1000 * 60 * 1440).toISOString(),
    slaResolutionDeadline: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 500).toISOString(),
    verifiedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    resolutionNotes: 'All pressures nominal at 36.2 PSI. Sign-off completed by Facility Director.',
    isSlaResponseBreached: false,
    isSlaResolutionBreached: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 2000).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    parts: [],
    timeEntries: [],
    auditLogs: []
  },
  {
    id: 'wo-106',
    organizationId: 'org-apex-1',
    workOrderNumber: 'WO-2026-0885',
    facilityId: 'fac-1',
    facilityName: 'Apex Tower Manhattan',
    title: 'Water Intrusion Reported on Floor 18 Mechanical Riser Chase',
    description: 'Building engineer reports minor pooling around condensate drain line near AHU-18-B. Suspected clogged trap.',
    status: 'NEW',
    priority: 'HIGH',
    category: 'CORRECTIVE_MAINTENANCE',
    estimatedDurationHours: 2.0,
    actualDurationHours: 0.0,
    slaResponseDeadline: new Date(Date.now() + 1000 * 60 * 45).toISOString(),
    slaResolutionDeadline: new Date(Date.now() + 1000 * 60 * 360).toISOString(),
    isSlaResponseBreached: false,
    isSlaResolutionBreached: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    parts: [],
    timeEntries: [],
    auditLogs: [
      {
        id: 'aud-601',
        organizationId: 'org-apex-1',
        entityName: 'WorkOrder',
        entityId: 'wo-106',
        action: 'CREATED',
        performedBy: 'David Kim (Customer)',
        performedByRole: 'CUSTOMER',
        timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
        newState: 'NEW',
        notes: 'Inbound customer ticket submitted via portal.',
      }
    ],
    comments: [
      {
        id: 'comm-601',
        entityId: 'wo-106',
        entityType: 'WORK_ORDER',
        authorId: 'user-cust-1',
        authorName: 'David Kim',
        authorRole: 'CUSTOMER',
        content: 'Noticed dripping from drop ceiling acoustic tiles right above the server rack corridor. Please treat with urgency.',
        createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
      }
    ],
    attachments: [
      {
        id: 'att-601',
        entityId: 'wo-106',
        entityType: 'WORK_ORDER',
        fileName: 'ceiling_leak_photo.jpg',
        fileSize: 245192,
        fileType: 'image/jpeg',
        url: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600&auto=format&fit=crop&q=60',
        uploadedBy: 'David Kim',
        uploadedByRole: 'CUSTOMER',
        createdAt: new Date(Date.now() - 1000 * 60 * 14).toISOString(),
        caption: 'Ceiling tile water intrusion photo',
      }
    ],
    assignmentHistory: []
  },
  {
    id: 'wo-107',
    organizationId: 'org-apex-1',
    workOrderNumber: 'WO-2026-0886',
    facilityId: 'fac-3',
    facilityName: 'Metro BioTech Research Facility',
    assetId: 'ast-4',
    assetName: 'Johnson Controls Metasys DDC Server',
    title: 'Exhaust Fume Hood Face Velocity Sensor Fault Lab 4G',
    description: 'Face velocity monitor alarm sounding intermittent 60 FPM low-flow alert. VAV sash position sensor potentiometer requires triage and recalibration.',
    status: 'TRIAGED',
    priority: 'HIGH',
    category: 'SAFETY_COMPLIANCE',
    estimatedDurationHours: 2.5,
    actualDurationHours: 0.0,
    slaResponseDeadline: new Date(Date.now() + 1000 * 60 * 120).toISOString(),
    slaResolutionDeadline: new Date(Date.now() + 1000 * 60 * 480).toISOString(),
    isSlaResponseBreached: false,
    isSlaResolutionBreached: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    parts: [],
    timeEntries: [],
    auditLogs: [
      {
        id: 'aud-701',
        organizationId: 'org-apex-1',
        entityName: 'WorkOrder',
        entityId: 'wo-107',
        action: 'STATUS_TRANSITION',
        performedBy: 'Marcus Chen',
        performedByRole: 'DISPATCHER',
        timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
        previousState: 'NEW',
        newState: 'TRIAGED',
        notes: 'Triaged by Dispatcher Marcus Chen. Verified chemical safety hood protocol.',
      }
    ],
    comments: [
      {
        id: 'comm-701',
        entityId: 'wo-107',
        entityType: 'WORK_ORDER',
        authorId: 'user-disp-1',
        authorName: 'Marcus Chen',
        authorRole: 'DISPATCHER',
        content: 'Fume hood safety override active. Priority escalated to HIGH for bio-containment safety.',
        createdAt: new Date(Date.now() - 1000 * 60 * 24).toISOString(),
      }
    ],
    attachments: [],
    assignmentHistory: []
  },
  {
    id: 'wo-108',
    organizationId: 'org-apex-1',
    workOrderNumber: 'WO-2026-0887',
    facilityId: 'fac-1',
    facilityName: 'Apex Tower Manhattan',
    assetId: 'ast-2',
    assetName: 'Otis SkyRise High-Speed Elevator Bank C',
    assignedTechnicianId: 'tech-1',
    assignedTechnicianName: 'Elena Reyes',
    title: 'Elevator Bank C Governor Sheave Cable Tension Alignment',
    description: 'Routine quarterly measurement of cable stretch and speed governor overspeed trip threshold test.',
    status: 'ACCEPTED',
    priority: 'MEDIUM',
    category: 'PREVENTIVE_MAINTENANCE',
    estimatedDurationHours: 3.0,
    actualDurationHours: 0.0,
    slaResponseDeadline: new Date(Date.now() + 1000 * 60 * 180).toISOString(),
    slaResolutionDeadline: new Date(Date.now() + 1000 * 60 * 720).toISOString(),
    isSlaResponseBreached: false,
    isSlaResolutionBreached: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    parts: [],
    timeEntries: [],
    auditLogs: [
      {
        id: 'aud-801',
        organizationId: 'org-apex-1',
        entityName: 'WorkOrder',
        entityId: 'wo-108',
        action: 'STATUS_TRANSITION',
        performedBy: 'Elena Reyes',
        performedByRole: 'TECHNICIAN',
        timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
        previousState: 'ASSIGNED',
        newState: 'ACCEPTED',
        notes: 'Elena Reyes accepted dispatch assignment.',
      }
    ],
    comments: [],
    attachments: [],
    assignmentHistory: [
      {
        id: 'asg-801',
        workOrderId: 'wo-108',
        technicianId: 'tech-1',
        technicianName: 'Elena Reyes',
        assignedBy: 'Marcus Chen',
        assignedByRole: 'DISPATCHER',
        assignedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
        notes: 'Priority elevator maintenance pass scheduled for after-hours.',
        status: 'ACTIVE',
      }
    ]
  },
  {
    id: 'wo-109',
    organizationId: 'org-apex-1',
    workOrderNumber: 'WO-2026-0860',
    facilityId: 'fac-1',
    facilityName: 'Apex Tower Manhattan',
    assetId: 'ast-1',
    assetName: 'Trane Centrifugal Chiller 500-Ton',
    assignedTechnicianId: 'tech-1',
    assignedTechnicianName: 'Elena Reyes',
    title: 'Refrigerant R-410A Annual Oil Spectrometry & Filter Core Swap',
    description: 'Completed annual oil analysis showing 0.02% moisture (nominal). Core replaced and vacuum tested at 500 microns.',
    status: 'CLOSED',
    priority: 'MEDIUM',
    category: 'PREVENTIVE_MAINTENANCE',
    estimatedDurationHours: 4.0,
    actualDurationHours: 3.8,
    slaResponseDeadline: new Date(Date.now() - 1000 * 60 * 5000).toISOString(),
    slaResolutionDeadline: new Date(Date.now() - 1000 * 60 * 4000).toISOString(),
    respondedAt: new Date(Date.now() - 1000 * 60 * 4900).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 4200).toISOString(),
    verifiedAt: new Date(Date.now() - 1000 * 60 * 4100).toISOString(),
    closedAt: new Date(Date.now() - 1000 * 60 * 4050).toISOString(),
    resolutionNotes: 'Oil spectrometry report verified within ASHRAE standards. Signed off by Lead Building Engineer.',
    isSlaResponseBreached: false,
    isSlaResolutionBreached: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 5200).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 4050).toISOString(),
    parts: [],
    timeEntries: [],
    auditLogs: [
      {
        id: 'aud-901',
        organizationId: 'org-apex-1',
        entityName: 'WorkOrder',
        entityId: 'wo-109',
        action: 'STATUS_TRANSITION',
        performedBy: 'Sarah Jenkins (Admin)',
        performedByRole: 'ADMIN',
        timestamp: new Date(Date.now() - 1000 * 60 * 4050).toISOString(),
        previousState: 'VERIFIED',
        newState: 'CLOSED',
        notes: 'Final administrative sign-off and closure.',
      }
    ],
    comments: [],
    attachments: [],
    assignmentHistory: []
  }
];

export const SEED_SERVICE_REQUESTS: ServiceRequest[] = [
  {
    id: 'sr-1',
    organizationId: 'org-apex-1',
    customerId: 'cust-1',
    customerName: 'Global Financial Holdings Corp',
    facilityId: 'fac-1',
    facilityName: 'Apex Tower Manhattan',
    assetId: 'ast-1',
    assetName: 'Trane Centrifugal Chiller 500-Ton',
    requestNumber: 'SR-2026-0041',
    title: 'Executive Boardroom Conference A/C Not Reaching Setpoint',
    description: 'Conference room 34B is set to 70F but room thermometer reads 78F during high-occupancy meetings. Chilled water VAV damper appears unresponsive.',
    priority: 'HIGH',
    status: 'PENDING_REVIEW',
    requestedDate: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString().split('T')[0],
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    requesterEmail: 'facilitymgr@globalfin.com',
    requesterName: 'David Kim',
    locationDetails: 'Floor 34, Suite 3400 Executive East Wing',
    comments: [
      {
        id: 'sr-c-1',
        entityId: 'sr-1',
        entityType: 'SERVICE_REQUEST',
        authorId: 'user-cust-1',
        authorName: 'David Kim',
        authorRole: 'CUSTOMER',
        content: 'Board of Directors convenes at 2:00 PM tomorrow. Urgent cooling restoration requested.',
        createdAt: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
      }
    ],
    attachments: [
      {
        id: 'sr-att-1',
        entityId: 'sr-1',
        entityType: 'SERVICE_REQUEST',
        fileName: 'thermostat_display.jpg',
        fileSize: 184910,
        fileType: 'image/jpeg',
        url: 'https://images.unsplash.com/photo-1545259741-2ea3ebf61fa3?w=600&auto=format&fit=crop&q=60',
        uploadedBy: 'David Kim',
        uploadedByRole: 'CUSTOMER',
        createdAt: new Date(Date.now() - 1000 * 60 * 58).toISOString(),
        caption: 'Wall thermostat showing 78F setpoint mismatch',
      }
    ]
  },
  {
    id: 'sr-2',
    organizationId: 'org-apex-1',
    customerId: 'cust-2',
    customerName: 'BioHealth Laboratories',
    facilityId: 'fac-3',
    facilityName: 'Metro BioTech Research Facility',
    assetId: 'ast-4',
    assetName: 'Johnson Controls Metasys DDC Server',
    requestNumber: 'SR-2026-0042',
    title: 'Emergency Eye-Wash Station Weekly ANSI Inspection Required',
    description: 'Routine compliance audit scheduled for tomorrow. Need certified verification of eye-wash flow rates across Lab Wings A and C.',
    priority: 'MEDIUM',
    status: 'PENDING_REVIEW',
    requestedDate: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString().split('T')[0],
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    requesterEmail: 'safety@biohealthlabs.com',
    requesterName: 'Dr. Aris Thorne',
    locationDetails: 'Lab Wing C, Station 4',
    comments: [],
    attachments: []
  }
];

export const SEED_NOTIFICATIONS: any[] = [
  {
    id: 'notif-1',
    organizationId: 'org-apex-1',
    type: 'NEW_SERVICE_REQUEST',
    title: 'New Service Request Intake',
    message: 'Horizon Financial Center submitted SR-2026-0041: Server Room 302 HVAC Overheating (HIGH Priority).',
    entityType: 'SERVICE_REQUEST',
    entityId: 'sr-1',
    targetRoles: ['ADMIN', 'DISPATCHER'],
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    link: 'service-requests',
  },
  {
    id: 'notif-2',
    organizationId: 'org-apex-1',
    type: 'SLA_AT_RISK',
    title: 'SLA Warning: Resolution Window < 60m',
    message: 'WO-2026-0002 (Centrifugal Chiller Surge) has 45 minutes remaining before SLA resolution breach.',
    entityType: 'WORK_ORDER',
    entityId: 'wo-2',
    targetRoles: ['ADMIN', 'DISPATCHER'],
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    link: 'work-orders',
  },
  {
    id: 'notif-3',
    organizationId: 'org-apex-1',
    userId: 'usr-tech-1',
    type: 'WORK_ORDER_ASSIGNED',
    title: 'New Dispatch Assignment',
    message: 'You have been dispatched to WO-2026-0001: Commercial Rooftop Unit #4 at Apex Commercial Tower.',
    entityType: 'WORK_ORDER',
    entityId: 'wo-1',
    targetRoles: ['TECHNICIAN'],
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    link: 'technician-portal',
  },
  {
    id: 'notif-4',
    organizationId: 'org-apex-1',
    type: 'LOW_INVENTORY',
    title: 'Inventory Stock Depletion',
    message: 'MERV-13 Pleated Filter (FIL-M13-2424) at Apex Commercial Tower has fallen below minimum reorder point.',
    entityType: 'INVENTORY',
    entityId: 'part-1',
    targetRoles: ['ADMIN', 'DISPATCHER'],
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    link: 'inventory',
  },
  {
    id: 'notif-5',
    organizationId: 'org-apex-1',
    userId: 'usr-cust-1',
    type: 'WORK_COMPLETED',
    title: 'Field Service Completed - Sign-off Required',
    message: 'WO-2026-0003 (Main Switchgear Thermographic Survey) has been marked COMPLETED. Please inspect and verify.',
    entityType: 'WORK_ORDER',
    entityId: 'wo-3',
    targetRoles: ['CUSTOMER'],
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    link: 'customer-portal',
  },
];

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    organizationId: 'org-apex-1',
    name: 'Global Financial Corp',
    contactPerson: 'David Kim',
    email: 'facilitymgr@globalfin.com',
    phone: '(555) 890-1234',
    tier: 'ENTERPRISE',
    slaTier: 'Mission-Critical 24/7 Enterprise Tier',
    primaryFacilityId: 'fac-1',
    primaryFacilityName: 'Apex Tower Manhattan',
    activeContract: 'CNT-2026-GF01',
    status: 'ACTIVE',
    openTicketsCount: 2,
    totalSpentYtd: 48500.00,
    address: '350 5th Avenue, Floors 12-45',
    city: 'New York',
    state: 'NY',
  },
  {
    id: 'cust-2',
    organizationId: 'org-apex-1',
    name: 'BioHealth Laboratories',
    contactPerson: 'Dr. Evelyn Reed',
    email: 'labops@biohealthlabs.org',
    phone: '(555) 781-9920',
    tier: 'ENTERPRISE',
    slaTier: 'BioHealth Labs Research Wing Strict SLA',
    primaryFacilityId: 'fac-3',
    primaryFacilityName: 'Metro BioTech Research Facility',
    activeContract: 'CNT-2026-BH02',
    status: 'ACTIVE',
    openTicketsCount: 1,
    totalSpentYtd: 36200.00,
    address: '88 Cambridge Science Park',
    city: 'Boston',
    state: 'MA',
  },
  {
    id: 'cust-3',
    organizationId: 'org-apex-1',
    name: 'Silicon Bay Innovation Partners',
    contactPerson: 'Marcus Vance',
    email: 'facilities@siliconbay.io',
    phone: '(555) 432-8811',
    tier: 'PREMIUM',
    slaTier: 'High Priority Standard Facility SLA',
    primaryFacilityId: 'fac-2',
    primaryFacilityName: 'Silicon Bay Innovation Campus',
    activeContract: 'CNT-2026-SB03',
    status: 'ACTIVE',
    openTicketsCount: 0,
    totalSpentYtd: 22800.00,
    address: '400 Technology Way',
    city: 'San Jose',
    state: 'CA',
  }
];

